[workspace]
members = [
    "node",
    "pallets/scbc",
    "pallets/validator-set",
#   "pallets/template",
#   "pallets/zk-snarks",
    "runtime",
]
resolver = "2"
[profile.release]
panic = "unwind"
